// Translation system
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'nav.help': 'Help',
    'nav.login': 'Login',
    'nav.register': 'Register',
    
    // Hero Section
    'hero.title': 'Welcome to E-Gramasevaka',
    'hero.subtitle': 'Digital Government Services at Your Fingertips',
    'hero.explore': 'Explore Services',
    'hero.getStarted': 'Get Started',
    'hero.testChatbot': 'Test Chatbot',
    
    // Features Section
    'features.title': 'Why Choose E-Gramasevaka?',
    'features.subtitle': 'Experience seamless access to government services with our digital platform',
    'features.fast.title': 'Fast & Efficient',
    'features.fast.desc': 'Get your certificates and documents processed quickly with our streamlined digital system.',
    'features.transparent.title': 'Transparent Process',
    'features.transparent.desc': 'Track your application status in real-time with complete transparency.',
    'features.secure.title': 'Secure & Safe',
    'features.secure.desc': 'Your data is protected with state-of-the-art security measures.',
    
    // Services Section
    'services.title': 'Popular Services',
    'services.subtitle': 'Access the most commonly requested government services',
    'services.birth.title': 'Birth Certificate',
    'services.birth.desc': 'Apply for your birth certificate online with our simplified process.',
    'services.learnMore': 'Learn More →',
    'services.viewAll': 'View All Services',
    
    // CTA Section
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Join thousands of citizens who are already using E-Gramasevaka',
    'cta.createAccount': 'Create Account',
    'cta.contactUs': 'Contact Us',
    
    // Footer
    'footer.description': 'Digital government services platform providing efficient and transparent access to various government services and certificates.',
    'footer.quickLinks': 'Quick Links',
    'footer.contactInfo': 'Contact Info',
    'footer.email': 'Email:',
    'footer.hotline': 'Hotline:',
    'footer.address': 'Address:',
    'footer.copyright': '© 2025 e-GramaSewa. All rights reserved.',
    
    // Chatbot
    'chatbot.title': 'e-GramaSewa Assistant',
    'chatbot.status': 'Online',
    'chatbot.welcome': '👋 Welcome to e-GramaSewa! I\'m your AI assistant. I can help you with:',
    'chatbot.registration': 'Registration',
    'chatbot.services': 'Services',
    'chatbot.track': 'Track Application',
    'chatbot.support': 'Support',
    'chatbot.suggestions': '💡 Try asking:',
    'chatbot.documents': 'What documents do I need?',
    'chatbot.processing': 'How long does it take to process an application?',
    'chatbot.fees': 'What are the fees?',
    'chatbot.contact': 'How to contact support?',
    'chatbot.placeholder': 'Ask me anything about e-GramaSewa...',
    'chatbot.powered': 'Powered by AI',
    'chatbot.messages': 'messages',
    
    // About Page
    'about.mission.title': 'Our Mission & Vision',
    'about.mission.heading': 'Mission',
    'about.mission.text': 'Our mission is to provide seamless, efficient, and transparent access to essential government services through a user-friendly digital platform. We aim to simplify and streamline the process for citizens to access government certificates, with a focus on accessibility, security, and reliability.',
    'about.vision.heading': 'Vision',
    'about.vision.text': 'Our vision is to create a digitally empowered Sri Lanka, where every citizen can easily access government services from anywhere, at any time. We strive to build a more inclusive, transparent, and responsive public service system that meets the needs of modern society.',
    'about.services.title': 'Available Services',
    'about.services.subtitle': 'Select the service you need and follow the simple steps to apply.',
    'about.birth.title': 'Birth Certificate',
    'about.birth.desc': 'Apply for your birth certificate online with our simplified process.',
    'about.birth.eligibility': 'Eligibility:',
    'about.birth.eligibility.text': 'Any Sri Lankan citizen',
    'about.birth.documents': 'Required Documents:',
    'about.birth.documents.text': 'National ID, Birth details (if available)',
    'about.birth.time': 'Processing Time:',
    'about.birth.time.text': '3-5 working days',
    'about.income.title': 'Income Certificate',
    'about.income.desc': 'Apply for your income certificate online with our simplified process.',
    'about.income.eligibility': 'Eligibility:',
    'about.income.eligibility.text': 'Employed individuals and businesses',
    'about.income.documents': 'Required Documents:',
    'about.income.documents.text': 'Pay slip, Tax returns (if applicable)',
    'about.income.time': 'Processing Time:',
    'about.income.time.text': '5-7 working days',
    'about.character.title': 'Character Certificate',
    'about.character.desc': 'Apply for your Character certificate online with our simplified process.',
    'about.character.eligibility': 'Eligibility:',
    'about.character.eligibility.text': 'Individuals seeking government-related positions',
    'about.character.documents': 'Required Documents:',
    'about.character.documents.text': 'National ID, Police clearance (if applicable)',
    'about.character.time': 'Processing Time:',
    'about.character.time.text': '7-10 working days',
    'about.grama.title': 'Grama Niladari Certificate',
    'about.grama.desc': 'Apply for your Grama Niladari certificate online with our simplified process.',
    'about.grama.eligibility': 'Eligibility:',
    'about.grama.eligibility.text': 'Residents of a specific Grama Niladari division',
    'about.grama.documents': 'Required Documents:',
    'about.grama.documents.text': 'Proof of address (e.g., utility bill, rental agreement)',
    'about.grama.time': 'Processing Time:',
    'about.grama.time.text': '5-7 working days',
    'about.learnMore': 'Learn More →',
    'about.viewAll': 'View All Services',
    
    // Service Page
    'service.title': 'Available Services',
    'service.subtitle': 'Select the service you need and follow the simple steps to apply.',
    'service.birth.title': 'Birth Certificate',
    'service.birth.desc': 'Apply for your birth certificate online with our simplified process.',
    'service.birth.eligibility': 'Eligibility:',
    'service.birth.eligibility.text': 'Any Sri Lankan citizen',
    'service.birth.documents': 'Required Documents:',
    'service.birth.documents.text': 'National ID, Birth details (if available)',
    'service.birth.howto': 'How to Apply:',
    'service.birth.howto.text': 'Complete the online form and upload necessary documents',
    'service.birth.timeline': 'Timeline:',
    'service.birth.timeline.text': '3-5 working days',
    'service.income.title': 'Income Certificate',
    'service.income.desc': 'Apply for your income certificate online with our simplified process.',
    'service.income.eligibility': 'Eligibility:',
    'service.income.eligibility.text': 'Employed individuals and businesses',
    'service.income.documents': 'Required Documents:',
    'service.income.documents.text': 'Pay slip, Tax returns (if applicable)',
    'service.income.howto': 'How to Apply:',
    'service.income.howto.text': 'Fill out the online application and attach required documents',
    'service.income.timeline': 'Timeline:',
    'service.income.timeline.text': '5-7 working days',
    'service.character.title': 'Character Certificate',
    'service.character.desc': 'Apply for your Character certificate online with our simplified process.',
    'service.character.eligibility': 'Eligibility:',
    'service.character.eligibility.text': 'Individuals seeking government-related positions',
    'service.character.documents': 'Required Documents:',
    'service.character.documents.text': 'National ID, Police clearance (if applicable)',
    'service.character.howto': 'How to Apply:',
    'service.character.howto.text': 'Complete the form and submit the necessary police clearance',
    'service.character.timeline': 'Timeline:',
    'service.character.timeline.text': '7-10 working days',
    'service.grama.title': 'Grama Niladari Certificate',
    'service.grama.desc': 'Apply for your Grama Niladari certificate online with our simplified process.',
    'service.grama.eligibility': 'Eligibility:',
    'service.grama.eligibility.text': 'Residents of a specific Grama Niladari division',
    'service.grama.documents': 'Required Documents:',
    'service.grama.documents.text': 'Proof of address (e.g., utility bill, rental agreement)',
    'service.grama.howto': 'How to Apply:',
    'service.grama.howto.text': 'Fill out the online form with proof of residence',
    'service.grama.timeline': 'Timeline:',
    'service.grama.timeline.text': '5-7 working days',
    'service.national.title': 'National Certificate Recommendation',
    'service.national.desc': 'Apply for a National Certificate for various purposes like educational or employment verification.',
    'service.national.eligibility': 'Eligibility:',
    'service.national.eligibility.text': 'Citizens with proof of identity',
    'service.national.documents': 'Required Documents:',
    'service.national.documents.text': 'National ID, Proof of Education or Employment',
    'service.national.howto': 'How to Apply:',
    'service.national.howto.text': 'Submit your details and upload the necessary documents online',
    'service.national.timeline': 'Timeline:',
    'service.national.timeline.text': '5-7 working days',
    'service.family.title': 'Family Composition Certificate',
    'service.family.desc': 'Get a certificate stating the details of your family members.',
    'service.family.eligibility': 'Eligibility:',
    'service.family.eligibility.text': 'Sri Lankan citizens who need proof of family composition',
    'service.family.documents': 'Required Documents:',
    'service.family.documents.text': 'National ID, Family details',
    'service.family.howto': 'How to Apply:',
    'service.family.howto.text': 'Complete the online form and provide your family details',
    'service.family.timeline': 'Timeline:',
    'service.family.timeline.text': '5-7 working days',
    'service.living.title': 'Living Certificate',
    'service.living.desc': 'Apply for a certificate verifying your living status for various legal purposes.',
    'service.living.eligibility': 'Eligibility:',
    'service.living.eligibility.text': 'Sri Lankan citizens',
    'service.living.documents': 'Required Documents:',
    'service.living.documents.text': 'National ID, Proof of residence',
    'service.living.howto': 'How to Apply:',
    'service.living.howto.text': 'Complete the form and submit necessary documents',
    'service.living.timeline': 'Timeline:',
    'service.living.timeline.text': '3-5 working days',
    'service.land.title': 'Confirmation for Land Use',
    'service.land.desc': 'Apply for confirmation of land use for agricultural, residential, or commercial purposes.',
    'service.land.eligibility': 'Eligibility:',
    'service.land.eligibility.text': 'Landowners or developers',
    'service.land.documents': 'Required Documents:',
    'service.land.documents.text': 'Land title, Purpose of land use',
    'service.land.howto': 'How to Apply:',
    'service.land.howto.text': 'Submit the form online and attach necessary documentation',
    'service.land.timeline': 'Timeline:',
    'service.land.timeline.text': '7-10 working days',
    'service.applyNow': 'Apply Now',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us for any inquiries, support, or feedback. We\'re here to help you with all your government service needs.',
    'contact.getInTouch': 'Get In Touch',
    'contact.office': 'Office Address',
    'contact.office.text': 'Government Office Complex<br>Colombo 07, Sri Lanka',
    'contact.phone': 'Phone Number',
    'contact.phone.text': '+94 11 234 5678<br>+94 11 234 5679',
    'contact.email': 'Email Address',
    'contact.email.text': 'support@egramasewa.lk<br>info@egramasewa.lk',
    'contact.hours': 'Working Hours',
    'contact.hours.text': 'Monday - Friday: 8:00 AM - 5:00 PM<br>Saturday: 8:00 AM - 1:00 PM',
    'contact.hotline': '24/7 Hotline',
    'contact.hotline.text': '1919 - Emergency Services<br>1920 - General Inquiries',
    'contact.sendMessage': 'Send us a Message',
    'contact.fullName': 'Full Name *',
    'contact.emailAddress': 'Email Address *',
    'contact.phoneNumber': 'Phone Number',
    'contact.subject': 'Subject *',
    'contact.selectSubject': 'Select a subject',
    'contact.general': 'General Inquiry',
    'contact.support': 'Technical Support',
    'contact.complaint': 'Complaint',
    'contact.suggestion': 'Suggestion',
    'contact.feedback': 'Feedback',
    'contact.other': 'Other',
    'contact.message': 'Message *',
    'contact.messagePlaceholder': 'Please describe your inquiry in detail...',
    'contact.send': 'Send Message',
    'contact.findUs': 'Find Us',
    'contact.mapComing': 'Interactive Map Coming Soon',
    'contact.mapAddress': 'Government Office Complex, Colombo 07',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faq1.question': 'How can I track my application status?',
    'contact.faq1.answer': 'You can track your application status by logging into your account and visiting the "Track Application" section. You\'ll receive real-time updates on your application progress.',
    'contact.faq2.question': 'What documents do I need for certificate applications?',
    'contact.faq2.answer': 'Required documents vary by certificate type. Generally, you\'ll need your National ID, proof of residence, and relevant supporting documents. Check the specific requirements for each service.',
    'contact.faq3.question': 'How long does it take to process applications?',
    'contact.faq3.answer': 'Processing times vary by service type. Birth certificates typically take 3-5 business days, while other certificates may take 5-10 business days. You\'ll receive notifications at each stage.',
    'contact.faq4.question': 'Can I apply for multiple certificates at once?',
    'contact.faq4.answer': 'Yes, you can apply for multiple certificates simultaneously. Each application will be processed independently, and you can track them separately in your dashboard.',
    'contact.faq5.question': 'What if I need help with the application process?',
    'contact.faq5.answer': 'Our support team is available 24/7 via the hotline (1919) and email. You can also visit our office during working hours for in-person assistance.',
    
    // Help Page
    'help.title': 'Help & Support',
    'help.subtitle': 'Find answers to your questions and get the support you need for all your government service needs.',
    'help.quickHelp': 'Quick Help',
    'help.quickHelpSubtitle': 'Get instant help with the most common tasks and questions',
    'help.createAccount': 'Create Account',
    'help.createAccountDesc': 'Learn how to create your e-GramaSewa account and get started with our services.',
    'help.getStarted': 'Get Started',
    'help.applyServices': 'Apply for Services',
    'help.applyServicesDesc': 'Step-by-step guide to apply for birth certificates, ID verification, and other services.',
    'help.viewServices': 'View Services',
    'help.trackApplication': 'Track Application',
    'help.trackApplicationDesc': 'Monitor your application status and get real-time updates on your requests.',
    'help.trackNow': 'Track Now',
    'help.commonIssues': 'Common Issues',
    'help.commonIssuesDesc': 'Find solutions to frequently encountered problems and technical issues.',
    'help.viewFAQ': 'View FAQ',
    'help.howToUse': 'How to Use e-GramaSewa',
    'help.howToUseSubtitle': 'Follow these simple steps to get started with our digital services',
    'help.step1': 'Create Account',
    'help.step1Desc': 'Register for a free account using your email address and personal information.',
    'help.step2': 'Verify Identity',
    'help.step2Desc': 'Complete identity verification using your National ID and other required documents.',
    'help.step3': 'Select Service',
    'help.step3Desc': 'Choose from our available government services and certificates.',
    'help.step4': 'Submit Application',
    'help.step4Desc': 'Fill out the application form and upload required documents.',
    'help.step5': 'Track Progress',
    'help.step5Desc': 'Monitor your application status and receive notifications at each stage.',
    'help.step6': 'Receive Certificate',
    'help.step6Desc': 'Download your digital certificate or collect it from the designated office.',
    'help.faq': 'Frequently Asked Questions',
    'help.faq1.question': 'How do I create an account on e-GramaSewa?',
    'help.faq1.answer': 'To create an account, click on the "Register" button in the top navigation, fill in your personal details, verify your email address, and complete the identity verification process using your National ID.',
    'help.faq2.question': 'What documents do I need for certificate applications?',
    'help.faq2.answer': 'Required documents vary by service type. Generally, you\'ll need your National ID, proof of residence, and relevant supporting documents. Check the specific requirements for each service before applying.',
    'help.faq3.question': 'How long does it take to process applications?',
    'help.faq3.answer': 'Processing times vary by service type. Birth certificates typically take 3-5 business days, while other certificates may take 5-10 business days. You\'ll receive notifications at each stage of the process.',
    'help.faq4.question': 'Can I track my application status?',
    'help.faq4.answer': 'Yes, you can track your application status by logging into your account and visiting the "Track Application" section. You\'ll receive real-time updates on your application progress.',
    'help.faq5.question': 'What if I forget my password?',
    'help.faq5.answer': 'Click on "Forgot Password" on the login page, enter your email address, and follow the instructions sent to your email to reset your password securely.',
    'help.faq6.question': 'Is my personal information secure?',
    'help.faq6.answer': 'Yes, we use state-of-the-art security measures including SSL encryption, secure servers, and strict data protection protocols to ensure your personal information is safe and secure.',
    'help.faq7.question': 'Can I apply for multiple certificates at once?',
    'help.faq7.answer': 'Yes, you can apply for multiple certificates simultaneously. Each application will be processed independently, and you can track them separately in your dashboard.',
    'help.faq8.question': 'What if I need help with the application process?',
    'help.faq8.answer': 'Our support team is available 24/7 via the hotline (1919) and email. You can also visit our office during working hours for in-person assistance.',
    'help.stillNeedHelp': 'Still Need Help?',
    'help.stillNeedHelpSubtitle': 'Contact our support team for personalized assistance',
    'help.callUs': 'Call Us',
    'help.callUsDesc': 'Speak directly with our support team',
    'help.emailSupport': 'Email Support',
    'help.emailSupportDesc': 'Send us your questions via email',
    'help.liveChat': 'Live Chat',
    'help.liveChatDesc': 'Chat with our support team online',
    'help.available247': 'Available 24/7',
    'help.visitOffice': 'Visit Office',
    'help.visitOfficeDesc': 'Get in-person assistance',
    'help.officeAddress': 'Government Office, Colombo',
    
    // User Manual Page
    'manual.title': 'User Manual',
    'manual.subtitle': 'Complete Guide to Using e-GramaSewa Digital Services',
    'manual.toc': 'Table of Contents',
    'manual.introduction': '1. Introduction',
    'manual.gettingStarted': '2. Getting Started',
    'manual.registration': '3. User Registration',
    'manual.login': '4. Login Process',
    'manual.services': '5. Available Services',
    'manual.customerGuide': '6. Customer Guide',
    'manual.gramaSewakaGuide': '7. Grama Sewaka Guide',
    'manual.adminGuide': '8. Admin Guide',
    'manual.troubleshooting': '9. Troubleshooting',
    'manual.contact': '10. Contact & Support',
    'manual.welcome': 'Welcome to e-GramaSewa',
    'manual.welcomeDesc': 'e-GramaSewa is a comprehensive digital platform that provides easy access to essential government services. Our mission is to simplify and streamline the process for citizens to access government certificates and services online.',
    'manual.fastEfficient': 'Fast & Efficient',
    'manual.fastEfficientDesc': 'Get your certificates and documents processed quickly with our streamlined digital system.',
    'manual.transparentProcess': 'Transparent Process',
    'manual.transparentProcessDesc': 'Track your application status in real-time with complete transparency.',
    'manual.secureSafe': 'Secure & Safe',
    'manual.secureSafeDesc': 'Your data is protected with state-of-the-art security measures.',
    'manual.systemRequirements': 'System Requirements',
    'manual.modernBrowser': 'Modern web browser (Chrome, Firefox, Safari, Edge)',
    'manual.internetConnection': 'Internet connection',
    'manual.validEmail': 'Valid email address',
    'manual.nationalId': 'National ID or relevant identification documents'
  },
  
  si: {
    // Navigation
    'nav.home': 'මුල් පිටුව',
    'nav.about': 'අප ගැන',
    'nav.services': 'සේවා',
    'nav.contact': 'සම්බන්ධතා',
    'nav.help': 'උදව්',
    'nav.login': 'පුරන්න',
    'nav.register': 'ලියාපදිංචි වන්න',
    
    // Hero Section
    'hero.title': 'ඊ-ග්‍රාම සේවා වෙත සාදරයෙන් පිළිගනිමු',
    'hero.subtitle': 'ඔබේ ඇඟිලි තුඩුවේ ඩිජිටල් රජයේ සේවා',
    'hero.explore': 'සේවා ගවේෂණය කරන්න',
    'hero.getStarted': 'ආරම්භ කරන්න',
    'hero.testChatbot': 'චැට්බොට් පරීක්ෂා කරන්න',
    
    // Features Section
    'features.title': 'ඊ-ග්‍රාම සේවා තෝරන්නේ ඇයි?',
    'features.subtitle': 'අපගේ ඩිජිටල් වේදිකාව සමඟ රජයේ සේවා වලට අඛණ්ඩ ප්‍රවේශය ලබා ගන්න',
    'features.fast.title': 'වේගවත් සහ කාර්යක්ෂම',
    'features.fast.desc': 'අපගේ සුවිශේෂී ඩිජිටල් පද්ධතිය සමඟ ඔබේ සහතික සහ ලේඛන ඉක්මනින් සකස් කරන්න.',
    'features.transparent.title': 'පාරදෘෂ්‍ය ක්‍රියාවලිය',
    'features.transparent.desc': 'සම්පූර්ණ පාරදෘෂ්‍යතාවය සමඟ ඔබේ අයදුම්පත් තත්වය කාලයාලුවේ ගමන් කරන්න.',
    'features.secure.title': 'ආරක්ෂිත සහ ආරක්ෂිත',
    'features.secure.desc': 'ඔබේ දත්ත රාජ්‍ය-කලා ආරක්ෂණ පියවරයන් සමඟ ආරක්ෂා කර ඇත.',
    
    // Services Section
    'services.title': 'ප්‍රසිද්ධ සේවා',
    'services.subtitle': 'වඩාත් ඉල්ලූ රජයේ සේවා වලට ප්‍රවේශ වන්න',
    'services.birth.title': 'උපත සහතිකය',
    'services.birth.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ උපත සහතිකය සඳහා අයදුම් කරන්න.',
    'services.learnMore': 'වැඩිදුර ඉගෙන ගන්න →',
    'services.viewAll': 'සියලුම සේවා බලන්න',
    
    // CTA Section
    'cta.title': 'ආරම්භ කිරීමට සූදානම්ද?',
    'cta.subtitle': 'දැනටමත් ඊ-ග්‍රාම සේවා භාවිතා කරන දහස් ගණනක් පුරවැසියන් සමඟ එකතු වන්න',
    'cta.createAccount': 'ගිණුම සාදන්න',
    'cta.contactUs': 'අප හා සම්බන්ධ වන්න',
    
    // Footer
    'footer.description': 'විවිධ රජයේ සේවා සහ සහතික වලට කාර්යක්ෂම සහ පාරදෘෂ්‍ය ප්‍රවේශය සපයන ඩිජිටල් රජයේ සේවා වේදිකාව.',
    'footer.quickLinks': 'ක්‍රියාකාරී සබැඳි',
    'footer.contactInfo': 'සම්බන්ධතා තොරතුරු',
    'footer.email': 'විද්‍යුත් තැපෑල:',
    'footer.hotline': 'හොට්ලයින්:',
    'footer.address': 'ලිපිනය:',
    'footer.copyright': '© 2025 ඊ-ග්‍රාම සේවා. සියලුම අයිතිවාසිකම් ඇවිරිණි.',
    
    // Chatbot
    'chatbot.title': 'ඊ-ග්‍රාම සේවා සහායක',
    'chatbot.status': 'අන්තර්ජාලයේ',
    'chatbot.welcome': '👋 ඊ-ග්‍රාම සේවා වෙත සාදරයෙන් පිළිගනිමු! මම ඔබේ AI සහායකයා. මට ඔබට උදව් කළ හැකිය:',
    'chatbot.registration': 'ලියාපදිංචි වීම',
    'chatbot.services': 'සේවා',
    'chatbot.track': 'අයදුම්පත ගමන් කරන්න',
    'chatbot.support': 'සහාය',
    'chatbot.suggestions': '💡 අසන්න:',
    'chatbot.documents': 'මට අවශ්‍ය ලේඛන මොනවාද?',
    'chatbot.processing': 'අයදුම්පතක් සකස් කිරීමට කොපමණ කාලයක් ගතවේද?',
    'chatbot.fees': 'ගාස්තු මොනවාද?',
    'chatbot.contact': 'සහාය ලබා ගන්නේ කෙසේද?',
    'chatbot.placeholder': 'ඊ-ග්‍රාම සේවා ගැන ඕනෑම දෙයක් මගෙන් අසන්න...',
    'chatbot.powered': 'AI මගින් බලගැන්වෙන',
    'chatbot.messages': 'පණිවිඩ',
    
    // About Page
    'about.mission.title': 'අපගේ මෙහෙවර සහ දර්ශනය',
    'about.mission.heading': 'මෙහෙවර',
    'about.mission.text': 'අපගේ මෙහෙවර වන්නේ ප්‍රවේශ්‍ය, ආරක්ෂිත සහ විශ්වසනීය අවධානයක් යොමු කරමින් පුරවැසියන්ට රජයේ සහතික වලට ප්‍රවේශ වීමේ ක්‍රියාවලිය සරල කිරීම සහ සුවිශේෂී කිරීමයි. පරිශීලක-හිතකාමී ඩිජිටල් වේදිකාවක් හරහා අත්‍යවශ්‍ය රජයේ සේවා වලට අඛණ්ඩ, කාර්යක්ෂම සහ පාරදෘෂ්‍ය ප්‍රවේශය සපයන අපගේ අරමුණයි.',
    'about.vision.heading': 'දර්ශනය',
    'about.vision.text': 'අපගේ දර්ශනය වන්නේ සෑම පුරවැසියෙකුටම ඕනෑම තැනක සිට, ඕනෑම වේලාවක රජයේ සේවා වලට පහසුවෙන් ප්‍රවේශ විය හැකි ඩිජිටල් බලගැන්වූ ශ්‍රී ලංකාවක් නිර්මාණය කිරීමයි. නූතන සමාජයේ අවශ්‍යතා සපුරාලන වඩාත් ඇතුළත්, පාරදෘෂ්‍ය සහ ප්‍රතිචාරාත්මක පොදු සේවා පද්ධතියක් ගොඩනැගීමට අප උත්සාහ කරමු.',
    'about.services.title': 'ලබා ගත හැකි සේවා',
    'about.services.subtitle': 'ඔබට අවශ්‍ය සේවාව තෝරාගෙන අයදුම් කිරීමට සරල පියවර අනුගමනය කරන්න.',
    'about.birth.title': 'උපත සහතිකය',
    'about.birth.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ උපත සහතිකය සඳහා අයදුම් කරන්න.',
    'about.birth.eligibility': 'දක්ෂතා:',
    'about.birth.eligibility.text': 'ඕනෑම ශ්‍රී ලාංකික පුරවැසියෙක්',
    'about.birth.documents': 'අවශ්‍ය ලේඛන:',
    'about.birth.documents.text': 'ජාතික හැඳුනුම්පත, උපතේ විස්තර (ඇත්නම්)',
    'about.birth.time': 'සකස් කිරීමේ කාලය:',
    'about.birth.time.text': 'කාර්ය දින 3-5',
    'about.income.title': 'ආදායම් සහතිකය',
    'about.income.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ ආදායම් සහතිකය සඳහා අයදුම් කරන්න.',
    'about.income.eligibility': 'දක්ෂතා:',
    'about.income.eligibility.text': 'රැකියාවේ නියුක්ත පුද්ගලයන් සහ ව්‍යාපාර',
    'about.income.documents': 'අවශ්‍ය ලේඛන:',
    'about.income.documents.text': 'වැටුප් පත්‍රය, බදු ආපසු ගෙවීම් (ඇත්නම්)',
    'about.income.time': 'සකස් කිරීමේ කාලය:',
    'about.income.time.text': 'කාර්ය දින 5-7',
    'about.character.title': 'චරිත සහතිකය',
    'about.character.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ චරිත සහතිකය සඳහා අයදුම් කරන්න.',
    'about.character.eligibility': 'දක්ෂතා:',
    'about.character.eligibility.text': 'රජයේ රැකියා සොයන පුද්ගලයන්',
    'about.character.documents': 'අවශ්‍ය ලේඛන:',
    'about.character.documents.text': 'ජාතික හැඳුනුම්පත, පොලිස් පැහැදිලි කිරීම (ඇත්නම්)',
    'about.character.time': 'සකස් කිරීමේ කාලය:',
    'about.character.time.text': 'කාර්ය දින 7-10',
    'about.grama.title': 'ග්‍රාම නිලධාරී සහතිකය',
    'about.grama.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ ග්‍රාම නිලධාරී සහතිකය සඳහා අයදුම් කරන්න.',
    'about.grama.eligibility': 'දක්ෂතා:',
    'about.grama.eligibility.text': 'නිශ්චිත ග්‍රාම නිලධාරී අංශයක වාසය කරන පුද්ගලයන්',
    'about.grama.documents': 'අවශ්‍ය ලේඛන:',
    'about.grama.documents.text': 'ලිපින සාක්ෂි (උදා: උපයෝගිතා බිල්පත්, කුලිය ගිවිසුම)',
    'about.grama.time': 'සකස් කිරීමේ කාලය:',
    'about.grama.time.text': 'කාර්ය දින 5-7',
    'about.learnMore': 'වැඩිදුර ඉගෙන ගන්න →',
    'about.viewAll': 'සියලුම සේවා බලන්න',
    
    // Service Page
    'service.title': 'ලබා ගත හැකි සේවා',
    'service.subtitle': 'ඔබට අවශ්‍ය සේවාව තෝරාගෙන අයදුම් කිරීමට සරල පියවර අනුගමනය කරන්න.',
    'service.birth.title': 'උපත සහතිකය',
    'service.birth.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ උපත සහතිකය සඳහා අයදුම් කරන්න.',
    'service.birth.eligibility': 'දක්ෂතා:',
    'service.birth.eligibility.text': 'ඕනෑම ශ්‍රී ලාංකික පුරවැසියෙක්',
    'service.birth.documents': 'අවශ්‍ය ලේඛන:',
    'service.birth.documents.text': 'ජාතික හැඳුනුම්පත, උපතේ විස්තර (ඇත්නම්)',
    'service.birth.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.birth.howto.text': 'අන්තර්ජාල පෝරමය සම්පූර්ණ කර අවශ්‍ය ලේඛන උඩුගත කරන්න',
    'service.birth.timeline': 'කාලසටහන:',
    'service.birth.timeline.text': 'කාර්ය දින 3-5',
    'service.income.title': 'ආදායම් සහතිකය',
    'service.income.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ ආදායම් සහතිකය සඳහා අයදුම් කරන්න.',
    'service.income.eligibility': 'දක්ෂතා:',
    'service.income.eligibility.text': 'රැකියාවේ නියුක්ත පුද්ගලයන් සහ ව්‍යාපාර',
    'service.income.documents': 'අවශ්‍ය ලේඛන:',
    'service.income.documents.text': 'වැටුප් පත්‍රය, බදු ආපසු ගෙවීම් (ඇත්නම්)',
    'service.income.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.income.howto.text': 'අන්තර්ජාල අයදුම්පත පුරවා අවශ්‍ය ලේඛන අමුණන්න',
    'service.income.timeline': 'කාලසටහන:',
    'service.income.timeline.text': 'කාර්ය දින 5-7',
    'service.character.title': 'චරිත සහතිකය',
    'service.character.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ චරිත සහතිකය සඳහා අයදුම් කරන්න.',
    'service.character.eligibility': 'දක්ෂතා:',
    'service.character.eligibility.text': 'රජයේ රැකියා සොයන පුද්ගලයන්',
    'service.character.documents': 'අවශ්‍ය ලේඛන:',
    'service.character.documents.text': 'ජාතික හැඳුනුම්පත, පොලිස් පැහැදිලි කිරීම (ඇත්නම්)',
    'service.character.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.character.howto.text': 'පෝරමය සම්පූර්ණ කර අවශ්‍ය පොලිස් පැහැදිලි කිරීම ඉදිරිපත් කරන්න',
    'service.character.timeline': 'කාලසටහන:',
    'service.character.timeline.text': 'කාර්ය දින 7-10',
    'service.grama.title': 'ග්‍රාම නිලධාරී සහතිකය',
    'service.grama.desc': 'අපගේ සරල ක්‍රියාවලිය සමඟ ඔබේ ග්‍රාම නිලධාරී සහතිකය සඳහා අයදුම් කරන්න.',
    'service.grama.eligibility': 'දක්ෂතා:',
    'service.grama.eligibility.text': 'නිශ්චිත ග්‍රාම නිලධාරී අංශයක වාසය කරන පුද්ගලයන්',
    'service.grama.documents': 'අවශ්‍ය ලේඛන:',
    'service.grama.documents.text': 'ලිපින සාක්ෂි (උදා: උපයෝගිතා බිල්පත්, කුලිය ගිවිසුම)',
    'service.grama.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.grama.howto.text': 'වාසස්ථාන සාක්ෂිය සමඟ අන්තර්ජාල පෝරමය පුරවන්න',
    'service.grama.timeline': 'කාලසටහන:',
    'service.grama.timeline.text': 'කාර්ය දින 5-7',
    'service.national.title': 'ජාතික සහතික නිර්දේශය',
    'service.national.desc': 'අධ්‍යාපනික හෝ රැකියා සත්‍යාපනය වැනි විවිධ අරමුණු සඳහා ජාතික සහතිකයක් සඳහා අයදුම් කරන්න.',
    'service.national.eligibility': 'දක්ෂතා:',
    'service.national.eligibility.text': 'හැඳුනුම් සාක්ෂියක් සහිත පුරවැසියන්',
    'service.national.documents': 'අවශ්‍ය ලේඛන:',
    'service.national.documents.text': 'ජාතික හැඳුනුම්පත, අධ්‍යාපන හෝ රැකියා සාක්ෂි',
    'service.national.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.national.howto.text': 'ඔබේ විස්තර ඉදිරිපත් කර අවශ්‍ය ලේඛන අන්තර්ජාලයෙන් උඩුගත කරන්න',
    'service.national.timeline': 'කාලසටහන:',
    'service.national.timeline.text': 'කාර්ය දින 5-7',
    'service.family.title': 'පවුල් සංයුතිය සහතිකය',
    'service.family.desc': 'ඔබේ පවුල් සාමාජිකයන්ගේ විස්තර සඳහන් කරන සහතිකයක් ලබා ගන්න.',
    'service.family.eligibility': 'දක්ෂතා:',
    'service.family.eligibility.text': 'පවුල් සංයුතිය සඳහා සාක්ෂි අවශ්‍ය ශ්‍රී ලාංකික පුරවැසියන්',
    'service.family.documents': 'අවශ්‍ය ලේඛන:',
    'service.family.documents.text': 'ජාතික හැඳුනුම්පත, පවුල් විස්තර',
    'service.family.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.family.howto.text': 'අන්තර්ජාල පෝරමය සම්පූර්ණ කර ඔබේ පවුල් විස්තර සපයන්න',
    'service.family.timeline': 'කාලසටහන:',
    'service.family.timeline.text': 'කාර්ය දින 5-7',
    'service.living.title': 'ජීවත් වීමේ සහතිකය',
    'service.living.desc': 'විවිධ නීතිමය අරමුණු සඳහා ඔබේ ජීවත් වීමේ තත්වය සත්‍යාපනය කරන සහතිකයක් සඳහා අයදුම් කරන්න.',
    'service.living.eligibility': 'දක්ෂතා:',
    'service.living.eligibility.text': 'ශ්‍රී ලාංකික පුරවැසියන්',
    'service.living.documents': 'අවශ්‍ය ලේඛන:',
    'service.living.documents.text': 'ජාතික හැඳුනුම්පත, වාසස්ථාන සාක්ෂි',
    'service.living.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.living.howto.text': 'පෝරමය සම්පූර්ණ කර අවශ්‍ය ලේඛන ඉදිරිපත් කරන්න',
    'service.living.timeline': 'කාලසටහන:',
    'service.living.timeline.text': 'කාර්ය දින 3-5',
    'service.land.title': 'භූමි භාවිතය සඳහා තහවුරු කිරීම',
    'service.land.desc': 'කෘෂිකාර්මික, නේවාසික හෝ වාණිජ අරමුණු සඳහා භූමි භාවිතය තහවුරු කිරීම සඳහා අයදුම් කරන්න.',
    'service.land.eligibility': 'දක්ෂතා:',
    'service.land.eligibility.text': 'භූමි හිමියන් හෝ සංවර්ධකයන්',
    'service.land.documents': 'අවශ්‍ය ලේඛන:',
    'service.land.documents.text': 'භූමි මුල් පත්‍රය, භූමි භාවිතයේ අරමුණ',
    'service.land.howto': 'අයදුම් කරන්නේ කෙසේද:',
    'service.land.howto.text': 'පෝරමය අන්තර්ජාලයෙන් ඉදිරිපත් කර අවශ්‍ය ලේඛන අමුණන්න',
    'service.land.timeline': 'කාලසටහන:',
    'service.land.timeline.text': 'කාර්ය දින 7-10',
    'service.applyNow': 'දැන් අයදුම් කරන්න',
    
    // Contact Page
    'contact.title': 'අප හා සම්බන්ධ වන්න',
    'contact.subtitle': 'ඕනෑම විමසීම්, සහාය හෝ ප්‍රතිචාර සඳහා අප හා සම්බන්ධ වන්න. ඔබේ සියලුම රජයේ සේවා අවශ්‍යතා සඳහා අපි මෙහි සිටිමු.',
    'contact.getInTouch': 'සම්බන්ධ වන්න',
    'contact.office': 'කාර්යාල ලිපිනය',
    'contact.office.text': 'රජයේ කාර්යාල සංකීර්ණය<br>කොළඹ 07, ශ්‍රී ලංකාව',
    'contact.phone': 'දුරකථන අංකය',
    'contact.phone.text': '+94 11 234 5678<br>+94 11 234 5679',
    'contact.email': 'විද්‍යුත් තැපෑල',
    'contact.email.text': 'support@egramasewa.lk<br>info@egramasewa.lk',
    'contact.hours': 'කාර්ය කාලය',
    'contact.hours.text': 'සඳුදා - සිකුරාදා: උදේ 8:00 - සවස 5:00<br>සෙනසුරාදා: උදේ 8:00 - දහවල් 1:00',
    'contact.hotline': '24/7 හොට්ලයින්',
    'contact.hotline.text': '1919 - හදිසි සේවා<br>1920 - සාමාන්‍ය විමසීම්',
    'contact.sendMessage': 'අපට පණිවිඩයක් යවන්න',
    'contact.fullName': 'සම්පූර්ණ නම *',
    'contact.emailAddress': 'විද්‍යුත් තැපෑල *',
    'contact.phoneNumber': 'දුරකථන අංකය',
    'contact.subject': 'විෂය *',
    'contact.selectSubject': 'විෂයක් තෝරන්න',
    'contact.general': 'සාමාන්‍ය විමසීම',
    'contact.support': 'තාක්ෂණික සහාය',
    'contact.complaint': 'පැමිණිල්ල',
    'contact.suggestion': 'යෝජනාව',
    'contact.feedback': 'ප්‍රතිචාරය',
    'contact.other': 'වෙනත්',
    'contact.message': 'පණිවිඩය *',
    'contact.messagePlaceholder': 'කරුණාකර ඔබේ විමසීම විස්තරාත්මකව විස්තර කරන්න...',
    'contact.send': 'පණිවිඩය යවන්න',
    'contact.findUs': 'අපව සොයා ගන්න',
    'contact.mapComing': 'අන්තර්ක්‍රියාකාරී සිතියම ඉක්මනින් පැමිණෙයි',
    'contact.mapAddress': 'රජයේ කාර්යාල සංකීර්ණය, කොළඹ 07',
    'contact.faq': 'නිතර අසන ප්‍රශ්න',
    'contact.faq1.question': 'මගේ අයදුම්පත් තත්වය ගමන් කරන්නේ කෙසේද?',
    'contact.faq1.answer': 'ඔබේ ගිණුමට පුරන්නෙන් සහ "අයදුම්පත ගමන් කරන්න" අංශයට පිවිසීමෙන් ඔබේ අයදුම්පත් තත්වය ගමන් කළ හැකිය. ඔබේ අයදුම්පත් ප්‍රගතිය පිළිබඳ කාලයාලුවේ යාවත්කාලීන කිරීම් ඔබට ලැබෙනු ඇත.',
    'contact.faq2.question': 'සහතික අයදුම්පත් සඳහා මට අවශ්‍ය ලේඛන මොනවාද?',
    'contact.faq2.answer': 'අවශ්‍ය ලේඛන සහතික වර්ගය අනුව වෙනස් වේ. සාමාන්‍යයෙන්, ඔබට ඔබේ ජාතික හැඳුනුම්පත, වාසස්ථාන සාක්ෂි සහ අදාළ සහාය ලේඛන අවශ්‍ය වේ. සෑම සේවාවක් සඳහාම නිශ්චිත අවශ්‍යතා පරීක්ෂා කරන්න.',
    'contact.faq3.question': 'අයදුම්පත් සකස් කිරීමට කොපමණ කාලයක් ගතවේද?',
    'contact.faq3.answer': 'සකස් කිරීමේ කාලය සේවා වර්ගය අනුව වෙනස් වේ. උපත සහතික සාමාන්‍යයෙන් කාර්ය දින 3-5 ක් ගතවන අතර, වෙනත් සහතික කාර්ය දින 5-10 ක් ගතවිය හැකිය. සෑම අදියරකදීම ඔබට දැනුම්දීම් ලැබෙනු ඇත.',
    'contact.faq4.question': 'මට එකවර සහතික කිහිපයක් සඳහා අයදුම් කළ හැකිද?',
    'contact.faq4.answer': 'ඔව්, ඔබට එකවර සහතික කිහිපයක් සඳහා අයදුම් කළ හැකිය. සෑම අයදුම්පතක්ම ස්වාධීනව සකස් කරනු ලබන අතර, ඔබට ඒවා ඔබේ ඩෑෂ්බෝඩ් හි වෙන වෙනම ගමන් කළ හැකිය.',
    'contact.faq5.question': 'අයදුම් ක්‍රියාවලිය සමඟ උදව් අවශ්‍ය නම් කුමක් කළ යුතුද?',
    'contact.faq5.answer': 'අපගේ සහාය කණ්ඩායම හොට්ලයින් (1919) සහ විද්‍යුත් තැපෑල හරහා 24/7 ලබා ගත හැකිය. පුද්ගලික සහාය සඳහා කාර්ය කාලය තුළ අපගේ කාර්යාලයටද පැමිණිය හැකිය.',
    
    // Help Page
    'help.title': 'උදව් සහ සහාය',
    'help.subtitle': 'ඔබේ ප්‍රශ්න වලට පිළිතුරු සොයා ගන්න සහ ඔබේ සියලුම රජයේ සේවා අවශ්‍යතා සඳහා අවශ්‍ය සහාය ලබා ගන්න.',
    'help.quickHelp': 'ක්‍රියාකාරී උදව්',
    'help.quickHelpSubtitle': 'වඩාත් පොදු කාර්යයන් සහ ප්‍රශ්න සමඟ ක්‍රියාකාරී උදව් ලබා ගන්න',
    'help.createAccount': 'ගිණුමක් සාදන්න',
    'help.createAccountDesc': 'ඔබේ ඊ-ග්‍රාම සේවා ගිණුම සාදන්නේ කෙසේද යන්න ඉගෙන ගෙන අපගේ සේවා සමඟ ආරම්භ කරන්න.',
    'help.getStarted': 'ආරම්භ කරන්න',
    'help.applyServices': 'සේවා සඳහා අයදුම් කරන්න',
    'help.applyServicesDesc': 'උපත සහතික, හැඳුනුම් සත්‍යාපනය සහ වෙනත් සේවා සඳහා අයදුම් කිරීම සඳහා පියවරෙන් පියවර මගපෙන්වීම.',
    'help.viewServices': 'සේවා බලන්න',
    'help.trackApplication': 'අයදුම්පත ගමන් කරන්න',
    'help.trackApplicationDesc': 'ඔබේ අයදුම්පත් තත්වය නිරීක්ෂණය කර ඔබේ ඉල්ලීම් පිළිබඳ කාලයාලුවේ යාවත්කාලීන කිරීම් ලබා ගන්න.',
    'help.trackNow': 'දැන් ගමන් කරන්න',
    'help.commonIssues': 'පොදු ගැටළු',
    'help.commonIssuesDesc': 'නිතර හමුවන ගැටළු සහ තාක්ෂණික ගැටළු සඳහා විසඳුම් සොයා ගන්න.',
    'help.viewFAQ': 'නිතර අසන ප්‍රශ්න බලන්න',
    'help.howToUse': 'ඊ-ග්‍රාම සේවා භාවිතා කරන්නේ කෙසේද',
    'help.howToUseSubtitle': 'අපගේ ඩිජිටල් සේවා සමඟ ආරම්භ කිරීම සඳහා මෙම සරල පියවර අනුගමනය කරන්න',
    'help.step1': 'ගිණුමක් සාදන්න',
    'help.step1Desc': 'ඔබේ විද්‍යුත් තැපෑල සහ පුද්ගලික තොරතුරු භාවිතා කරමින් නොමිලේ ගිණුමක් සඳහා ලියාපදිංචි වන්න.',
    'help.step2': 'හැඳුනුම් සත්‍යාපනය කරන්න',
    'help.step2Desc': 'ඔබේ ජාතික හැඳුනුම්පත සහ වෙනත් අවශ්‍ය ලේඛන භාවිතා කරමින් හැඳුනුම් සත්‍යාපනය සම්පූර්ණ කරන්න.',
    'help.step3': 'සේවාව තෝරන්න',
    'help.step3Desc': 'අපගේ ලබා ගත හැකි රජයේ සේවා සහ සහතික වලින් තෝරන්න.',
    'help.step4': 'අයදුම්පත ඉදිරිපත් කරන්න',
    'help.step4Desc': 'අයදුම්පත පෝරමය පුරවා අවශ්‍ය ලේඛන උඩුගත කරන්න.',
    'help.step5': 'ප්‍රගතිය ගමන් කරන්න',
    'help.step5Desc': 'ඔබේ අයදුම්පත් තත්වය නිරීක්ෂණය කර සෑම අදියරකදීම දැනුම්දීම් ලබා ගන්න.',
    'help.step6': 'සහතිකය ලබා ගන්න',
    'help.step6Desc': 'ඔබේ ඩිජිටල් සහතිකය බාගත කරන්න හෝ නියමිත කාර්යාලයෙන් එය එකතු කරන්න.',
    'help.faq': 'නිතර අසන ප්‍රශ්න',
    'help.faq1.question': 'ඊ-ග්‍රාම සේවා වෙත ගිණුමක් සාදන්නේ කෙසේද?',
    'help.faq1.answer': 'ගිණුමක් සාදීම සඳහා, ඉහළ සංචාලනයේ "ලියාපදිංචි වන්න" බොත්තම ක්ලික් කරන්න, ඔබේ පුද්ගලික විස්තර පුරවන්න, ඔබේ විද්‍යුත් තැපෑල සත්‍යාපනය කරන්න, සහ ඔබේ ජාතික හැඳුනුම්පත භාවිතා කරමින් හැඳුනුම් සත්‍යාපන ක්‍රියාවලිය සම්පූර්ණ කරන්න.',
    'help.faq2.question': 'සහතික අයදුම්පත් සඳහා මට අවශ්‍ය ලේඛන මොනවාද?',
    'help.faq2.answer': 'අවශ්‍ය ලේඛන සේවා වර්ගය අනුව වෙනස් වේ. සාමාන්‍යයෙන්, ඔබට ඔබේ ජාතික හැඳුනුම්පත, වාසස්ථාන සාක්ෂි සහ අදාළ සහාය ලේඛන අවශ්‍ය වේ. අයදුම් කිරීමට පෙර සෑම සේවාවක් සඳහාම නිශ්චිත අවශ්‍යතා පරීක්ෂා කරන්න.',
    'help.faq3.question': 'අයදුම්පත් සකස් කිරීමට කොපමණ කාලයක් ගතවේද?',
    'help.faq3.answer': 'සකස් කිරීමේ කාලය සේවා වර්ගය අනුව වෙනස් වේ. උපත සහතික සාමාන්‍යයෙන් කාර්ය දින 3-5 ක් ගතවන අතර, වෙනත් සහතික කාර්ය දින 5-10 ක් ගතවිය හැකිය. ක්‍රියාවලියේ සෑම අදියරකදීම ඔබට දැනුම්දීම් ලැබෙනු ඇත.',
    'help.faq4.question': 'මගේ අයදුම්පත් තත්වය ගමන් කළ හැකිද?',
    'help.faq4.answer': 'ඔව්, ඔබේ ගිණුමට පුරන්නෙන් සහ "අයදුම්පත ගමන් කරන්න" අංශයට පිවිසීමෙන් ඔබේ අයදුම්පත් තත්වය ගමන් කළ හැකිය. ඔබේ අයදුම්පත් ප්‍රගතිය පිළිබඳ කාලයාලුවේ යාවත්කාලීන කිරීම් ඔබට ලැබෙනු ඇත.',
    'help.faq5.question': 'මගේ මුරපදය අමතක වුවහොත් කුමක් කළ යුතුද?',
    'help.faq5.answer': 'පුරන්න පිටුවේ "මුරපදය අමතක වී ඇත" ක්ලික් කරන්න, ඔබේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න, සහ ඔබේ විද්‍යුත් තැපෑලට යවන ලද උපදෙස් අනුගමනය කරමින් ඔබේ මුරපදය ආරක්ෂිතව යළි සැකසීම කරන්න.',
    'help.faq6.question': 'මගේ පුද්ගලික තොරතුරු ආරක්ෂිතද?',
    'help.faq6.answer': 'ඔව්, ඔබේ පුද්ගලික තොරතුරු ආරක්ෂිත සහ ආරක්ෂිත බව සහතික කිරීම සඳහා අපි SSL සංකේතනය, ආරක්ෂිත සේවාදායක, සහ දැඩි දත්ත ආරක්ෂණ ප්‍රොටෝකෝල ඇතුළු රාජ්‍ය-අතිශය ආරක්ෂණ පියවර භාවිතා කරමු.',
    'help.faq7.question': 'මට එකවර සහතික කිහිපයක් සඳහා අයදුම් කළ හැකිද?',
    'help.faq7.answer': 'ඔව්, ඔබට එකවර සහතික කිහිපයක් සඳහා අයදුම් කළ හැකිය. සෑම අයදුම්පතක්ම ස්වාධීනව සකස් කරනු ලබන අතර, ඔබට ඒවා ඔබේ ඩෑෂ්බෝඩ් හි වෙන වෙනම ගමන් කළ හැකිය.',
    'help.faq8.question': 'අයදුම් ක්‍රියාවලිය සමඟ උදව් අවශ්‍ය නම් කුමක් කළ යුතුද?',
    'help.faq8.answer': 'අපගේ සහාය කණ්ඩායම හොට්ලයින් (1919) සහ විද්‍යුත් තැපෑල හරහා 24/7 ලබා ගත හැකිය. පුද්ගලික සහාය සඳහා කාර්ය කාලය තුළ අපගේ කාර්යාලයටද පැමිණිය හැකිය.',
    'help.stillNeedHelp': 'තවමත් උදව් අවශ්‍යද?',
    'help.stillNeedHelpSubtitle': 'පුද්ගලීකරණය කළ සහාය සඳහා අපගේ සහාය කණ්ඩායම හා සම්බන්ධ වන්න',
    'help.callUs': 'අපට කතා කරන්න',
    'help.callUsDesc': 'අපගේ සහාය කණ්ඩායම සමඟ සෘජුව කතා කරන්න',
    'help.emailSupport': 'විද්‍යුත් තැපෑල සහාය',
    'help.emailSupportDesc': 'විද්‍යුත් තැපෑල හරහා ඔබේ ප්‍රශ්න අපට යවන්න',
    'help.liveChat': 'සජීවී කතාබහ',
    'help.liveChatDesc': 'අන්තර්ජාලයෙන් අපගේ සහාය කණ්ඩායම සමඟ කතාබහ කරන්න',
    'help.available247': '24/7 ලබා ගත හැකිය',
    'help.visitOffice': 'කාර්යාලයට පැමිණෙන්න',
    'help.visitOfficeDesc': 'පුද්ගලික සහාය ලබා ගන්න',
    'help.officeAddress': 'රජයේ කාර්යාලය, කොළඹ',
    
    // User Manual Page
    'manual.title': 'පරිශීලක අත්පොත',
    'manual.subtitle': 'ඊ-ග්‍රාම සේවා ඩිජිටල් සේවා භාවිතා කිරීම සඳහා සම්පූර්ණ මගපෙන්වීම',
    'manual.toc': 'අන්තර්ගතයේ වගුව',
    'manual.introduction': '1. හැඳින්වීම',
    'manual.gettingStarted': '2. ආරම්භ කිරීම',
    'manual.registration': '3. පරිශීලක ලියාපදිංචි කිරීම',
    'manual.login': '4. පුරන්න ක්‍රියාවලිය',
    'manual.services': '5. ලබා ගත හැකි සේවා',
    'manual.customerGuide': '6. ගනුදෙනුකරු මගපෙන්වීම',
    'manual.gramaSewakaGuide': '7. ග්‍රාම සේවක මගපෙන්වීම',
    'manual.adminGuide': '8. පරිපාලක මගපෙන්වීම',
    'manual.troubleshooting': '9. ගැටළු විසඳීම',
    'manual.contact': '10. සම්බන්ධතා සහ සහාය',
    'manual.welcome': 'ඊ-ග්‍රාම සේවා වෙත සාදරයෙන් පිළිගනිමු',
    'manual.welcomeDesc': 'ඊ-ග්‍රාම සේවා යනු අත්‍යවශ්‍ය රජයේ සේවා වෙත පහසු ප්‍රවේශය සපයන සවිස්තරාත්මක ඩිජිටල් වේදිකාවකි. රජයේ සහතික සහ සේවා වෙත ප්‍රවේශ වීම සඳහා පුරවැසියන්ගේ ක්‍රියාවලිය සරල කිරීම සහ ක්‍රියාකාරී කිරීම අපගේ අරමුණයි.',
    'manual.fastEfficient': 'වේගවත් සහ ක්‍රියාකාරී',
    'manual.fastEfficientDesc': 'අපගේ ක්‍රියාකාරී ඩිජිටල් පද්ධතිය සමඟ ඔබේ සහතික සහ ලේඛන ඉක්මනින් සකස් කරන්න.',
    'manual.transparentProcess': 'පාරදෘෂ්‍ය ක්‍රියාවලිය',
    'manual.transparentProcessDesc': 'සම්පූර්ණ පාරදෘෂ්‍යතාවයක් සමඟ ඔබේ අයදුම්පත් තත්වය කාලයාලුවේ ගමන් කරන්න.',
    'manual.secureSafe': 'ආරක්ෂිත සහ ආරක්ෂිත',
    'manual.secureSafeDesc': 'ඔබේ දත්ත රාජ්‍ය-අතිශය ආරක්ෂණ පියවර සමඟ ආරක්ෂා කර ඇත.',
    'manual.systemRequirements': 'පද්ධති අවශ්‍යතා',
    'manual.modernBrowser': 'නූතන වෙබ් බ්‍රවුසරය (Chrome, Firefox, Safari, Edge)',
    'manual.internetConnection': 'අන්තර්ජාල සම්බන්ධතාවය',
    'manual.validEmail': 'වලංගු විද්‍යුත් තැපෑල',
    'manual.nationalId': 'ජාතික හැඳුනුම්පත හෝ අදාළ හැඳුනුම් ලේඛන'
  }
};

// Current language
let currentLanguage = 'en';

// Language change function
function changeLanguage() {
  const langSelect = document.getElementById("language-select");
  if (langSelect) {
  const selected = langSelect.value;
    if (selected === 'sinhala.html') {
      currentLanguage = 'si';
    } else {
      currentLanguage = 'en';
    }
    translatePage();
  }
}

// Toggle language function
function toggleLanguage() {
  currentLanguage = currentLanguage === 'en' ? 'si' : 'en';
  
  const langSelect = document.getElementById("language-select");
  if (langSelect) {
    langSelect.value = currentLanguage === 'si' ? 'sinhala.html' : 'english.html';
  }
  translatePage();
}

// Translate page content
function translatePage() {
  const elements = document.querySelectorAll('[data-translate]');
  
  elements.forEach(element => {
    const key = element.getAttribute('data-translate');
    if (translations[currentLanguage] && translations[currentLanguage][key]) {
      element.textContent = translations[currentLanguage][key];
    }
  });
  
  // Translate placeholders
  const placeholderElements = document.querySelectorAll('[data-translate-placeholder]');
  placeholderElements.forEach(element => {
    const key = element.getAttribute('data-translate-placeholder');
    if (translations[currentLanguage] && translations[currentLanguage][key]) {
      element.placeholder = translations[currentLanguage][key];
    }
  });
  
  // Update language select
  const langSelect = document.getElementById("language-select");
  if (langSelect) {
    langSelect.value = currentLanguage === 'si' ? 'sinhala.html' : 'english.html';
  }
}

// Simple fade-in on scroll (lightweight)
document.addEventListener('DOMContentLoaded', function() {
  // Initialize translation system
  translatePage();
  
const faders = document.querySelectorAll(".fade-in");

  if (faders.length > 0 && 'IntersectionObserver' in window) {
const appearOptions = {
      threshold: 0.1,
  rootMargin: "0px 0px -50px 0px"
};

    const appearOnScroll = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add("visible");
          appearOnScroll.unobserve(entry.target);
    }
  });
}, appearOptions);

faders.forEach(fader => {
  appearOnScroll.observe(fader);
});
  }

  // Simple button click animation
  const buttons = document.querySelectorAll(".btn");
  buttons.forEach(btn => {
  btn.addEventListener("click", () => {
    btn.classList.add("clicked");
      setTimeout(() => btn.classList.remove("clicked"), 200);
    });
  });
});
